name: Deploy to VM
on:
  push: { branches: [main] }
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          port:     ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -e
            APP=~/database/DB_lab4
            if [ -d "$APP/.git" ]; then
              git -C "$APP" pull --ff-only
            else
              git clone --depth=1 -b main https://github.com/DenisFolyush/database "$APP"
            fi
            python3 -m venv "$APP/venv" 2>/dev/null || true
            "$APP/venv/bin/pip" -q install -U pip wheel
            [ -f "$APP/requirements.txt" ] && "$APP/venv/bin/pip" install -r "$APP/requirements.txt" || true
            # опційно: розкоментуй наступний рядок, коли треба перезапустити сервіс
            # sudo systemctl restart flask
            echo "OK"
