name: Deploy to VM
on:
  push: { branches: [main] }
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy 
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          port:     ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -e
            APP=~/database/DB_lab4
            [ -d "$APP/.git" ] || { echo "❌ $APP не знайдено (repo must already exist)"; exit 1; }
            git -C "$APP" pull --ff-only
            # venv лише якщо нема
            [ -d "$APP/venv" ] || python3 -m venv "$APP/venv"
            "$APP/venv/bin/pip" -q install -U pip wheel
            [ -f "$APP/requirements.txt" ] && "$APP/venv/bin/pip" install -r "$APP/requirements.txt" || true
            echo "✅ Deployed without restart"
