name: Deploy to VM
on:
  push: { branches: [main] }
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy (no clone)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          port:     ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -e
            BASE=~/database
            APP="$BASE"
            if [ -d "$BASE/.git" ]; then
              echo "→ repo at $BASE"
            elif [ -d "$BASE/DB_lab4/.git" ]; then
              APP="$BASE/DB_lab4"
              echo "→ repo at $APP"
            else
              echo "❌ Git repo not found at $BASE or $BASE/DB_lab4 (run initial clone once on the VM)"; exit 1
            fi

            git -C "$APP" pull --ff-only

            # venv тільки якщо відсутній
            [ -d "$APP/venv" ] || python3 -m venv "$APP/venv"
            "$APP/venv/bin/pip" -q install -U pip wheel
            [ -f "$APP/requirements.txt" ] && "$APP/venv/bin/pip" install -r "$APP/requirements.txt" || true

            echo "✅ Deployed without restart (APP=$APP)"
